---
auth:
  required: true
  queryParams: {}
  headerParams: {}
  apiKeysPath: null
  headersPath: null
  oauthPath: null
testConfiguration:
  operations:
  - testPath: /youtube/v3/search
    operationId: youtube.search.list
    method: get
    testParameters:
    - name: part
      in: query
      weight: null
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: channelId
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: channelType
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - channelTypeUnspecified
          - any
          - show
          objectValues: null
        valid: true
    - name: eventType
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - none
          - upcoming
          - live
          - completed
          objectValues: null
        valid: true
    - name: forContentOwner
      in: query
      weight: 0.5
      generators:
      - type: RandomBoolean
        genParameters: []
        valid: true
    - name: forDeveloper
      in: query
      weight: 0.5
      generators:
      - type: RandomBoolean
        genParameters: []
        valid: true
    - name: forMine
      in: query
      weight: 0.5
      generators:
      - type: RandomBoolean
        genParameters: []
        valid: true
    - name: location
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: locationRadius
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: maxResults
      in: query
      weight: 0.5
      generators:
      - type: RandomNumber
        genParameters:
        - name: type
          values:
          - integer
          objectValues: null
        - name: min
          values:
          - 0
          objectValues: null
        - name: max
          values:
          - 50
          objectValues: null
        valid: true
    - name: onBehalfOfContentOwner
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: order
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - searchSortUnspecified
          - date
          - rating
          - viewCount
          - relevance
          - title
          - videoCount
          objectValues: null
        valid: true
    - name: pageToken
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: publishedAfter
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: publishedBefore
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: q
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: regionCode
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: relatedToVideoId
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: relevanceLanguage
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: safeSearch
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - safeSearchSettingUnspecified
          - none
          - moderate
          - strict
          objectValues: null
        valid: true
    - name: topicId
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: type
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: videoCaption
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - videoCaptionUnspecified
          - any
          - closedCaption
          - none
          objectValues: null
        valid: true
    - name: videoCategoryId
      in: query
      weight: 0.5
      generators:
      - type: RandomEnglishWord
        genParameters:
        - name: maxWords
          values:
          - 1
          objectValues: null
        valid: true
    - name: videoDefinition
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - any
          - standard
          - high
          objectValues: null
        valid: true
    - name: videoDimension
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - any
          - 2d
          - 3d
          objectValues: null
        valid: true
    - name: videoDuration
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - videoDurationUnspecified
          - any
          - short
          - medium
          - long
          objectValues: null
        valid: true
    - name: videoEmbeddable
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - videoEmbeddableUnspecified
          - any
          - "true"
          objectValues: null
        valid: true
    - name: videoLicense
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - any
          - youtube
          - creativeCommon
          objectValues: null
        valid: true
    - name: videoSyndicated
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - videoSyndicatedUnspecified
          - any
          - "true"
          objectValues: null
        valid: true
    - name: videoType
      in: query
      weight: 0.5
      generators:
      - type: RandomInputValue
        genParameters:
        - name: values
          values:
          - videoTypeUnspecified
          - any
          - movie
          - episode
          objectValues: null
        valid: true
    expectedResponse: 200
